<a href="https://colab.research.google.com/github/Sabirbinsakander/Data_Science_Practice_Folder/blob/main/Class_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Python Numpy**

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
import numpy

In [4]:
a = numpy.array([1,2,3])
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
temp = [1, 2, 3, "Asif", None, True, 3.5] ##List

In [7]:
len(a)

3

In [8]:
a[1]

np.int64(2)

In [9]:
a[2]

np.int64(3)

# 1D Array

In [15]:
import numpy as np

In [16]:
a = np.array([1,2,3])
print(a)

[1 2 3]


### **2D Matrix**

In [17]:
temp_a = np.array([ [1,2,3], [4,5,6] ])
print(temp_a)

[[1 2 3]
 [4 5 6]]


## 3D **Matrix**

In [18]:
temp_a = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
print(temp_a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# **Indexing And Slicing**

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a[11]

np.int64(12)

In [20]:
type(a[2:7])

numpy.ndarray

In [21]:
a[-3:-1]

array([10, 11])

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
temp_a = a[a>5]
print(temp_a)

[ 6  7  8  9 10 11 12]


In [25]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
temp_a = a[a%2==0]
print(temp_a)

[ 2  4  6  8 10 12]


In [26]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
temp_a = a[(a%2==0) & (a > 5)]
print(temp_a)

[ 6  8 10 12]


In [12]:
a = np.array([ [1,2,3],[4,6,7] ])
print(a)

[[1 2 3]
 [4 6 7]]


In [13]:
a = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
a[1][0]

array([7, 8, 9])

## **Shape & Size of an ndarray**

In [30]:
 a = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
 print(a.shape)
 print(a)
 print(a.size)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [31]:
a = np.array([ [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ],
             [[[10,20,30], [40,50,60]], [[70,80,90], [100,110,120]]]])
print(a.shape)
print(a)
print(a.size)

(2, 2, 2, 3)
[[[[  1   2   3]
   [  4   5   6]]

  [[  7   8   9]
   [ 10  11  12]]]


 [[[ 10  20  30]
   [ 40  50  60]]

  [[ 70  80  90]
   [100 110 120]]]]
24


In [33]:
a = np.array([1,2,3])
print(a.shape)

(3,)


### *Create a Matrix*

In [34]:
a = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
a.shape



(2, 2, 3)

In [35]:
np.zeros(2)

array([0., 0.])

In [37]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
a =np.array([  [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ] )
a.shape

(2, 2, 3)

In [40]:
0.33 * np.ones((2,2,3))

array([[[0.33, 0.33, 0.33],
        [0.33, 0.33, 0.33]],

       [[0.33, 0.33, 0.33],
        [0.33, 0.33, 0.33]]])

In [42]:
temp = np.zeros((3,3))
temp[0][0] = 1
temp[1][1] = 1
temp[2][2] = 1
print(temp)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
np.arange(4)

array([0, 1, 2, 3])

In [46]:
np.arange(2,9,2)

array([2, 4, 6, 8])

# **Adding, removing,and sorting elements**

In [47]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

In [48]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6],[7,8]])
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [50]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6],[7,8]])
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
a = np.array([  [1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)
np.delete(a, 0, 1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [52]:
a = np.array([  [1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)
np.delete(a, 0)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
a = np.array([  [1,2,3], [4,5,6], [7,8,9], [10,11,12]])
a[0][0] = 0
print(a)


[[ 0  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
a = np.array([ [3,2,4], [4,5,2],[7,4,7]])
print(a)
np.sort(a)

[[3 2 4]
 [4 5 2]
 [7 4 7]]


array([[2, 3, 4],
       [2, 4, 5],
       [4, 7, 7]])

In [56]:
a = np.array([[3,2,4],[7,4,7],[4,5,2]])
sort_a = np.sort(a)
print(sort_a)
revers_a = np.flip(sort_a)
print(revers_a)

[[2 3 4]
 [4 7 7]
 [2 4 5]]
[[5 4 2]
 [7 7 4]
 [4 3 2]]


In [ ]:
a = np.array([[3,2,4],[7,4,7],[4,5,2]])

np.transpose(a)

# **Reshape an ndarray**

In [58]:
a = np.array([1,2,3,4,5,6,7,8,9])

a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a= np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,4))
print(a.reshape(4,2))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [61]:
a = np.array([  [1,2,3], [4,5,6], [7,8,9], [10,11,12]])
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a.reshape(3,2)

# **Flatten an ndarray**

In [64]:
a = np.array([  [1,2,3], [4,5,6], [7,8,9], [10,11,12]])
x = a.flatten()
len(x)

12

## **Creating array from exiting data**

In [65]:
a = np.array([1,2,3,4,5,6,7,8])
type(a[2:5])

numpy.ndarray

# **Basic array operations**

In [69]:
a = np.array([1.1,2,3,4,5,6,7], dtype=int)
a
a

array([1, 2, 3, 4, 5, 6, 7])

In [72]:
np.ones(2)

array([1., 1.])

In [71]:
data = np.array([1,2])
ones =np.ones(2, dtype=int)
print(ones)
data + ones

[1 1]


array([2, 3])

In [73]:
data -ones

array([0, 1])

In [74]:
data * ones

array([1, 2])

In [77]:
data / ones

array([1., 2.])

# ***Max/Min/Sum***

In [80]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [82]:
a = np.array([[1,2], [3,4]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

10
[4 6]
[3 7]


In [83]:
a = np.array([1,2,3,4])
print(a.max())
print(a.min())

4
1


# **Pandas**

In [85]:
pip install pandas

In [86]:
import pandas as pd

# **Object creation**

In [88]:
a = pd.Series([10,20,30,40,50])
print(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [91]:
a = pd.Series ([10,"Asif", None, 40, True])
print(a)

0      10
1    Asif
2    None
3      40
4    True
dtype: object


In [95]:
dictionary = {"day1" : 422, "day2":370, "day3": 398}

myvar = pd.Series(dictionary)
print(myvar)
print(myvar['day2'])

day1    422
day2    370
day3    398
dtype: int64
370


In [96]:
date = {
    "Weight":[70, 56,68,92,85],
    "Height":[175, 178, 162, 177, 169]
}
df = pd.DataFrame(date)
print(df)

   Weight  Height
0      70     175
1      56     178
2      68     162
3      92     177
4      85     169
