In [ ]:
print("hello world")

hello world


Second Lecture

In [ ]:
x = 3
y = "Beautiful weater"

print(x)
print(y)

3
Beautiful weater


Declear Data type

In [ ]:
x = str(5)
print(x,type(x))

5 <class 'str'>


In [ ]:
int_x = float(5)
print(x, type(x))

5 <class 'str'>


Naming condition

In [ ]:
our_list=["item_1","item_2","item_3","item_4","item_5"]
print(type(our_list))
print(our_list)

<class 'list'>
['item_1', 'item_2', 'item_3', 'item_4', 'item_5']


In [ ]:
#can containt diffrent data type
our_list=["item_1","item_2","item_3"]
print(our_list)


['item_1', 'item_2', 'item_3']


In [ ]:
#can containt duplicate value
our_list=["item_1","item_2","item_3","item_3"]
print(our_list)

['item_1', 'item_2', 'item_3', 'item_3']


In [ ]:
#value Chageable
our_list[0]="new value"
print(our_list)

['new value', 'item_2', 'item_3', 'item_3']


In [ ]:
demo_dict={
    "month":"march",
    "day":23,
    "year":2023
}
print(demo_dict)


{'month': 'march', 'day': 23, 'year': 2023}


In [ ]:
print(f"all keys: {demo_dict.keys()}")
print(f"all values: {demo_dict.values()}")

all keys: dict_keys(['month', 'day', 'year'])
all values: dict_values(['march', 23, 2023])


In [ ]:
our_tuple=("item_1","item_2","item_3")
print(our_tuple)
print(type(our_tuple))

('item_1', 'item_2', 'item_3')
<class 'tuple'>


In [ ]:
a_age = 5
b_age = 8
if(a_age <= b_age):
  print("a is not older then b")

a is not older then b


In [ ]:
a_height = 4.56
b_height = 5.55

if(a_height == b_height):
  print("a and b are same height")
elif(a_height > b_height):
  print("a is taller then b")
else:
  print("a is shorter then b")

a is shorter then b


In [ ]:
a = 4
b = 4
c = 8
d = 8
if(a == b and c == d):
  print("a and b are equal and c and d are equal")
else:
  print("Both the condition arr true")

a and b are equal and c and d are equal


In [ ]:
a = 4
b = 4
c = 7
d = 8
if(a == b or c == d):
  print("a and b are equal and c and d are equal")
else:
  print("Both the condition arr true")

a and b are equal and c and d are equal


In [ ]:
a_age = 5
b_age = 8
c_age = 10
if(c_age > b_age):
  print("c is the older than b")
  if(c_age > a_age):
    print("c is the older than a")
  else:
    print("c is not the oldest")
else:
  print("c is not the oldest")

c is the older than b
c is the older than a


In [ ]:
i = 1
while i < 6:
  print(i)
  i=i+1



1
2
3
4
5


In [ ]:
i = 1
sum = 0

while i <= 5:
  sum = sum + i
  i = i + 1

print(sum)

15


In [ ]:
items = ["item_1","item_2","item_3"]
for x in items:
  print(x)

item_1
item_2
item_3


In [ ]:
for x in "Data science":
  print(x)

D
a
t
a
 
s
c
i
e
n
c
e


In [ ]:
start = 1
end = 10
increment = 2

for i in range (start, end, increment):
  print(i)


1
3
5
7
9


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [1]:
def print_function():
  print("Hello world")


In [2]:
print_function()

Hello world


In [ ]:
num_1 = 5
num_2 = 10
sum = num_1 + num_2
print(sum)

In [7]:
def sum_numbers(x, y):
 z = x + y
 return(z)

In [8]:
num_1 = 5
num_2 = 10
sum = sum_numbers(num_1, num_2)
print(sum)

15


In [4]:
import math
print(math.sqrt(58))

7.615773105863909


In [10]:
import pandas as pd
data = {
    "speed":[420, 380, 390],
    "time":[50, 40, 45]
    }
df = pd.DataFrame(data)
df

speed  time
0    420    50
1    380    40
2    390    45

In [13]:
import pandas as pd
data = {
    "speed":[420, 380, 390],
    "time":[50, 40, 45]
    }
df = pd.DataFrame(data, index = ["period1", "period2", "period3"])
df

speed  time
period1    420    50
period2    380    40
period3    390    45

In [14]:
data = [[420, 430],[340, 234],[570, 40]]
df = pd.DataFrame(data, columns = ["speed", "time"], index = ["period1", "period2", "period3"])
df


speed  time
period1    420   430
period2    340   234
period3    570    40

In [15]:
df = pd.read_csv("Tesla.csv")
df

Date        Open        High         Low       Close    Volume  \
0     6/29/2010   19.000000   25.000000   17.540001   23.889999  18766300   
1     6/30/2010   25.790001   30.420000   23.299999   23.830000  17187100   
2      7/1/2010   25.000000   25.920000   20.270000   21.959999   8218800   
3      7/2/2010   23.000000   23.100000   18.709999   19.200001   5139800   
4      7/6/2010   20.000000   20.000000   15.830000   16.110001   6866900   
...         ...         ...         ...         ...         ...       ...   
1687  3/13/2017  244.820007  246.850006  242.779999  246.169998   3010700   
1688  3/14/2017  246.110001  258.119995  246.020004  258.000000   7575500   
1689  3/15/2017  257.000000  261.000000  254.270004  255.729996   4816600   
1690  3/16/2017  262.399994  265.750000  259.059998  262.049988   7100400   
1691  3/17/2017  264.000000  265.329987  261.200012  261.500000   6475900   

       Adj Close  
0      23.889999  
1      23.830000  
2      21.959999  
3      19.200001  
4      16.110001  
...          ...  
1687  246.169998  
1688  258.000000  
1689  255.729996  
1690  262.049988  
1691  261.500000  

[1692 rows x 7 columns]

In [17]:
import pandas as pd
df = pd.read_csv("Tesla.csv")
df.head(5)

Date       Open   High        Low      Close    Volume  Adj Close
0  6/29/2010  19.000000  25.00  17.540001  23.889999  18766300  23.889999
1  6/30/2010  25.790001  30.42  23.299999  23.830000  17187100  23.830000
2   7/1/2010  25.000000  25.92  20.270000  21.959999   8218800  21.959999
3   7/2/2010  23.000000  23.10  18.709999  19.200001   5139800  19.200001
4   7/6/2010  20.000000  20.00  15.830000  16.110001   6866900  16.110001

In [18]:
import pandas as pd
df = pd.read_csv("Tesla.csv")
df.tail(5)

Date        Open        High         Low       Close   Volume  \
1687  3/13/2017  244.820007  246.850006  242.779999  246.169998  3010700   
1688  3/14/2017  246.110001  258.119995  246.020004  258.000000  7575500   
1689  3/15/2017  257.000000  261.000000  254.270004  255.729996  4816600   
1690  3/16/2017  262.399994  265.750000  259.059998  262.049988  7100400   
1691  3/17/2017  264.000000  265.329987  261.200012  261.500000  6475900   

       Adj Close  
1687  246.169998  
1688  258.000000  
1689  255.729996  
1690  262.049988  
1691  261.500000

In [19]:
df.head(5)

Date       Open   High        Low      Close    Volume  Adj Close
0  6/29/2010  19.000000  25.00  17.540001  23.889999  18766300  23.889999
1  6/30/2010  25.790001  30.42  23.299999  23.830000  17187100  23.830000
2   7/1/2010  25.000000  25.92  20.270000  21.959999   8218800  21.959999
3   7/2/2010  23.000000  23.10  18.709999  19.200001   5139800  19.200001
4   7/6/2010  20.000000  20.00  15.830000  16.110001   6866900  16.110001

In [20]:
df.tail(5)

Date        Open        High         Low       Close   Volume  \
1687  3/13/2017  244.820007  246.850006  242.779999  246.169998  3010700   
1688  3/14/2017  246.110001  258.119995  246.020004  258.000000  7575500   
1689  3/15/2017  257.000000  261.000000  254.270004  255.729996  4816600   
1690  3/16/2017  262.399994  265.750000  259.059998  262.049988  7100400   
1691  3/17/2017  264.000000  265.329987  261.200012  261.500000  6475900   

       Adj Close  
1687  246.169998  
1688  258.000000  
1689  255.729996  
1690  262.049988  
1691  261.500000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1692 non-null   object 
 1   Open       1692 non-null   float64
 2   High       1692 non-null   float64
 3   Low        1692 non-null   float64
 4   Close      1692 non-null   float64
 5   Volume     1692 non-null   int64  
 6   Adj Close  1692 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 92.7+ KB


In [22]:
df.describe()

Open         High          Low        Close        Volume  \
count  1692.000000  1692.000000  1692.000000  1692.000000  1.692000e+03   
mean    132.441572   134.769698   129.996223   132.428658  4.270741e+06   
std      94.309923    95.694914    92.855227    94.313187  4.295971e+06   
min      16.139999    16.629999    14.980000    15.800000  1.185000e+05   
25%      30.000000    30.650000    29.215000    29.884999  1.194350e+06   
50%     156.334999   162.370002   153.150002   158.160004  3.180700e+06   
75%     220.557495   224.099999   217.119999   220.022503  5.662100e+06   
max     287.670013   291.420013   280.399994   286.040009  3.716390e+07   

         Adj Close  
count  1692.000000  
mean    132.428658  
std      94.313187  
min      15.800000  
25%      29.884999  
50%     158.160004  
75%     220.022503  
max     286.040009

In [37]:
df.head(5)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [38]:
df.corr()

ValueError: could not convert string to float: 'Mazda RX4'

In [26]:
df = pd.read_csv("mtcars.csv")
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [27]:
import pandas as pd
df = pd.read_csv("mtcars.csv")
df.head(5)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [28]:
df.tail(5)

model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [30]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [34]:
df.head(6)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
5     1

In [36]:
df.corr()

ValueError: could not convert string to float: 'Mazda RX4'

In [39]:
import pandas as pd

df = pd.read_csv("mtcars.csv")

# Selecting only numerical columns for correlation calculation
numerical_df = df.select_dtypes(include=['number'])

# Calculate the correlation on the numerical data
correlation_matrix = numerical_df.corr()

print(correlation_matrix)

           mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  

In [40]:
df.groupby(by=["am"]).mean()

TypeError: agg function failed [how->mean,dtype->object]

In [41]:
df.groupby(by=["cyl"]).max()

model   mpg   disp   hp  drat     wt   qsec  vs  am  gear  \
cyl                                                                         
4          Volvo 142E  33.9  146.7  113  4.93  3.190  22.90   1   1     5   
6             Valiant  21.4  258.0  175  3.92  3.460  20.22   1   1     5   
8    Pontiac Firebird  19.2  472.0  335  4.22  5.424  18.00   0   1     5   

     carb  
cyl        
4       2  
6       6  
8       8

In [42]:
df[df["gear"]== 3].describe()

mpg        cyl        disp          hp       drat         wt  \
count  15.000000  15.000000   15.000000   15.000000  15.000000  15.000000   
mean   16.106667   7.466667  326.300000  176.133333   3.132667   3.892600   
std     3.371618   1.187234   94.852735   47.689272   0.273665   0.832993   
min    10.400000   4.000000  120.100000   97.000000   2.760000   2.465000   
25%    14.500000   8.000000  275.800000  150.000000   3.035000   3.450000   
50%    15.500000   8.000000  318.000000  180.000000   3.080000   3.730000   
75%    18.400000   8.000000  380.000000  210.000000   3.180000   3.957500   
max    21.500000   8.000000  472.000000  245.000000   3.730000   5.424000   

            qsec         vs    am  gear       carb  
count  15.000000  15.000000  15.0  15.0  15.000000  
mean   17.692000   0.200000   0.0   3.0   2.666667  
std     1.349916   0.414039   0.0   0.0   1.175139  
min    15.410000   0.000000   0.0   3.0   1.000000  
25%    17.035000   0.000000   0.0   3.0   2.000000  
50%    17.420000   0.000000   0.0   3.0   3.000000  
75%    17.990000   0.000000   0.0   3.0   4.000000  
max    20.220000   1.000000   0.0   3.0   4.000000

# **Numpy **

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)

[1 2 3 4 5 6 7]


Higher Dimentional Array

In [9]:
dim_0  = np.array(1)
print(dim_0)

1


In [45]:
dim_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(dim_2)

[[1 2 3]
 [4 5 6]]


In [48]:
dim_3 = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
print(dim_3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
print(dim_3.ndim)

3


In [51]:
a = np.array([2, 3, 4])
b = np.array([10, 20, 30])


In [52]:
b-a

array([ 8, 17, 26])

In [53]:
b/a

array([5.        , 6.66666667, 7.5       ])

In [54]:
speed = np.array([9.8, 9.2, 11.5, 10.5, 10.2, 11, 9.2, 9.9, 9, 11.1])

speed < 10

array([ True,  True, False, False, False, False,  True,  True,  True,
       False])

In [55]:
studen_distrubution = np.array(["Asia", "South Africa", "Africa","Oceania","Asia", "Asia","North America", "Asia","Europe", "Africa", "Asia"])
studen_distrubution == "Asia"

array([ True, False, False, False,  True,  True, False,  True, False,
       False,  True])

In [57]:
speed.sum()

np.float64(101.39999999999999)

In [58]:
matrix_1 = np.array([[5, 6],[8, 7]])
print(matrix_1)

[[5 6]
 [8 7]]


In [60]:
matrix_2 = np.array([[1, 2],[3, 4]])
print(matrix_2)

[[1 2]
 [3 4]]


In [61]:
matrix_1*matrix_2

array([[ 5, 12],
       [24, 28]])

In [63]:
normal_matrix = np.array([[5, 6, 4], [8, 7, 9], [1, 2, 3]])
print(normal_matrix)

[[5 6 4]
 [8 7 9]
 [1 2 3]]


In [64]:
transpose_matrix = np.array([[5, 8, 1],[6, 7, 2], [4, 9, 3]])
print(transpose_matrix)

[[5 8 1]
 [6 7 2]
 [4 9 3]]


In [65]:
normal_matrix.transpose()

array([[5, 8, 1],
       [6, 7, 2],
       [4, 9, 3]])

In [10]:
import numpy as np
arr = np.array(["Cricket", "Football", "Tennis", "Basketball"])

arr[0]

np.str_('Cricket')

In [69]:
arr[-2]

np.str_('Tennis')

In [77]:
studen_distrubution = np.array([["Asia", "South Africa", "Africa","Oceania","Asia"], ["Asia","North America", "Asia","Europe", "Africa"]])

studen_distrubution[1, 3]

np.str_('Europe')

In [78]:
student_distribution = np.array([[["g1_roll_1", "g1_roll_2", "g3_roll_3"],[58, 69, 78]],[["g2_roll1","g2_roll2","g2_roll3"],[80, 45, 98]]])
print(student_distribution[0, 0, 1], student_distribution[0, 1, 1])


g1_roll_2 69


In [81]:
studen_distrubution = np.array([["Asia", "South Africa", "Africa","Oceania","Asia"], ["Asia","North America", "Asia","Europe", "Africa"]])
studen_distrubution == [studen_distrubution == "Asia"]

array([[[False, False, False, False, False],
        [False, False, False, False, False]]])

In [82]:
studen_distrubution == "Asia"

array([[ True, False, False, False,  True],
       [ True, False,  True, False, False]])

In [83]:
studen_distrubution = np.array([["Asia", "South Africa", "Africa","Oceania","Asia"], ["Asia","North America", "Asia","Europe", "Africa"]])
studen_names =np.array([["A","B", "C", "D", "E"], ["F", "G", "H", "I", "J"]])

studen_names[studen_distrubution == "Asia"]

array(['A', 'E', 'F', 'H'], dtype='<U1')

In [11]:
student_name = np.array(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"])


In [12]:
student_name[3:7]

array(['D', 'E', 'F', 'G'], dtype='<U1')

In [13]:
student_name[5:]

array(['F', 'G', 'H', 'I', 'J'], dtype='<U1')

In [14]:
student_name[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [15]:
student_distribution = np.array([["Asia", "South Africa", "Africa","Oceania","Asia"], ["Asia","North America", "Asia","Europe", "Africa"]])
student_distribution[0, 1:4]

array(['South Africa', 'Africa', 'Oceania'], dtype='<U13')

In [16]:
student_name[4:7:2]

array(['E', 'G'], dtype='<U1')

In [17]:
import numpy as np
arr = np.array([[["A", "B", "C", "D","E"],["F","G","H","I","J"]]])
arr.shape

(1, 2, 5)

In [20]:
arr = np.array([1, 2, 3, 4],ndmin = 4)
print(arr)

[[[[1 2 3 4]]]]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)

(12,)


In [22]:
arr.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
arr.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
import numpy as np
g1 = np.array(["A", "B", "c"])
g2 = np.array(["D","E", "G"])

In [28]:
joined_array = np.concatenate((g1, g2))
print(joined_array)

In [34]:
g1 = np.array([["A","B","C"],["D","E","G"]])
g2 = np.array ([["a", "b", "c"],["d", "e", "g"]])
joined_array = np.concatenate((g1, g2))
joined_array

array([['A', 'B', 'C'],
       ['D', 'E', 'G'],
       ['a', 'b', 'c'],
       ['d', 'e', 'g']], dtype='<U1')

In [36]:
joined_array = np.concatenate((g1, g2), axis = 1)
joined_array


array([['A', 'B', 'C', 'a', 'b', 'c'],
       ['D', 'E', 'G', 'd', 'e', 'g']], dtype='<U1')

In [37]:
arr = np.array(["A", "B", "C", "D", "E", "G"])
split_array = np.array_split(arr, 2)
split_array

[array(['A', 'B', 'C'], dtype='<U1'), array(['D', 'E', 'G'], dtype='<U1')]

In [38]:
split_array[0]

array(['A', 'B', 'C'], dtype='<U1')